# -*- coding: utf-8 -*-

"""
mergedapi

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""
from mergedapi.api_helper import APIHelper
from mergedapi.models.accountidentifier import Accountidentifier
from mergedapi.models.authentication import Authentication
from mergedapi.models.fields import Fields


class CreateATargetRequest(object):

    """Implementation of the 'CreateATargetRequest' model.

    Details of the target that you want to create.

    Attributes:
        accountidentifier (Accountidentifier): The ID of the authenticating
            billing account, in the format
            `{"billingaccountid":"1234567890-12345"}`.
        billingaccountid (string): The ID of the authenticating billing
            account.
        kind (string): Identifies the resource kind. Targets are ts.target.
        address (string): The endpoint for notifications or data streams. The
            format depends on the selected `addressscheme`.<br />`streamrest`
            requires a `host:port` value <br />`streamawsiot` requres a valid
            ARN.
        addressscheme (string): The transport format. Valid values are: <br
            />streamawsiot - streamed data to an AWS account <br />streamrest
            - streamed REST data to a defined endpoint
        fields (Fields): TODO: type description here.
        description (string): Descriptive information about the target.
        externalid (string): Security identification string created by a POST
            /targets/actions/newextid request.
        name (string): Name of the target.
        region (string): AWS region value.
        key_1 (string): oAuth 2.0 bearer token.
        oauth (Authentication): OAUTH 2 token and refresh token for TS to
            stream events to Target

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "accountidentifier": 'accountidentifier',
        "billingaccountid": 'billingaccountid',
        "kind": 'kind',
        "address": 'address',
        "addressscheme": 'addressscheme',
        "fields": 'fields',
        "description": 'description',
        "externalid": 'externalid',
        "name": 'name',
        "region": 'region',
        "key_1": 'key1',
        "oauth": 'oauth'
    }

    _optionals = [
        'accountidentifier',
        'billingaccountid',
        'kind',
        'address',
        'addressscheme',
        'fields',
        'description',
        'externalid',
        'name',
        'region',
        'key_1',
        'oauth',
    ]

    def __init__(self,
                 accountidentifier=APIHelper.SKIP,
                 billingaccountid=APIHelper.SKIP,
                 kind=APIHelper.SKIP,
                 address=APIHelper.SKIP,
                 addressscheme=APIHelper.SKIP,
                 fields=APIHelper.SKIP,
                 description=APIHelper.SKIP,
                 externalid=APIHelper.SKIP,
                 name=APIHelper.SKIP,
                 region=APIHelper.SKIP,
                 key_1=APIHelper.SKIP,
                 oauth=APIHelper.SKIP):
        """Constructor for the CreateATargetRequest class"""

        # Initialize members of the class
        if accountidentifier is not APIHelper.SKIP:
            self.accountidentifier = accountidentifier 
        if billingaccountid is not APIHelper.SKIP:
            self.billingaccountid = billingaccountid 
        if kind is not APIHelper.SKIP:
            self.kind = kind 
        if address is not APIHelper.SKIP:
            self.address = address 
        if addressscheme is not APIHelper.SKIP:
            self.addressscheme = addressscheme 
        if fields is not APIHelper.SKIP:
            self.fields = fields 
        if description is not APIHelper.SKIP:
            self.description = description 
        if externalid is not APIHelper.SKIP:
            self.externalid = externalid 
        if name is not APIHelper.SKIP:
            self.name = name 
        if region is not APIHelper.SKIP:
            self.region = region 
        if key_1 is not APIHelper.SKIP:
            self.key_1 = key_1 
        if oauth is not APIHelper.SKIP:
            self.oauth = oauth 

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Creates an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if dictionary is None:
            return None

        # Extract variables from the dictionary

        accountidentifier = Accountidentifier.from_dictionary(dictionary.get('accountidentifier')) if 'accountidentifier' in dictionary.keys() else APIHelper.SKIP
        billingaccountid = dictionary.get("billingaccountid") if dictionary.get("billingaccountid") else APIHelper.SKIP
        kind = dictionary.get("kind") if dictionary.get("kind") else APIHelper.SKIP
        address = dictionary.get("address") if dictionary.get("address") else APIHelper.SKIP
        addressscheme = dictionary.get("addressscheme") if dictionary.get("addressscheme") else APIHelper.SKIP
        fields = Fields.from_dictionary(dictionary.get('fields')) if 'fields' in dictionary.keys() else APIHelper.SKIP
        description = dictionary.get("description") if dictionary.get("description") else APIHelper.SKIP
        externalid = dictionary.get("externalid") if dictionary.get("externalid") else APIHelper.SKIP
        name = dictionary.get("name") if dictionary.get("name") else APIHelper.SKIP
        region = dictionary.get("region") if dictionary.get("region") else APIHelper.SKIP
        key_1 = dictionary.get("key1") if dictionary.get("key1") else APIHelper.SKIP
        oauth = Authentication.from_dictionary(dictionary.get('oauth')) if 'oauth' in dictionary.keys() else APIHelper.SKIP
        # Return an object of this model
        return cls(accountidentifier,
                   billingaccountid,
                   kind,
                   address,
                   addressscheme,
                   fields,
                   description,
                   externalid,
                   name,
                   region,
                   key_1,
                   oauth)
