# -*- coding: utf-8 -*-

"""
mergedapi

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class DataCenterDistributionEnum(object):

    """Implementation of the 'DataCenterDistributionEnum' enum.

    Supported Kubernetes distribution for the selected cloud provider

    Attributes:
        ENUM_UPSTREAM KUBERNETES: TODO: type description here.
        ENUM_AMAZON EKS DISTRO: TODO: type description here.

    """

    ENUM_UPSTREAM_KUBERNETES = 'Upstream Kubernetes'

    ENUM_AMAZON_EKS_DISTRO = 'Amazon EKS distro'
