# -*- coding: utf-8 -*-

"""
mergedapi

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class DataUnitEnum(object):

    """Implementation of the 'DataUnit' enum.

    Unit of time

    Attributes:
        SECOND: TODO: type description here.
        MINUTE: TODO: type description here.
        HOUR: TODO: type description here.
        DAY: TODO: type description here.

    """

    SECOND = 'SECOND'

    MINUTE = 'MINUTE'

    HOUR = 'HOUR'

    DAY = 'DAY'
