# -*- coding: utf-8 -*-

"""
mergedapi

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class DeploymentTypeEnum(object):

    """Implementation of the 'DeploymentTypeEnum' enum.

    default MEC platform for deploying service

    Attributes:
        PUBLICMEC: TODO: type description here.
        PRIVATEMEC: TODO: type description here.
        ONPREMISEMEC: TODO: type description here.

    """

    PUBLICMEC = 'PublicMEC'

    PRIVATEMEC = 'PrivateMEC'

    ONPREMISEMEC = 'OnPremiseMEC'
