# -*- coding: utf-8 -*-

"""
mergedapi

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class EndPointAccessTypeEnum(object):

    """Implementation of the 'EndPointAccessTypeEnum' enum.

    TODO: type enum description here.

    Attributes:
        PRIVATE: TODO: type description here.
        PUBLIC: TODO: type description here.
        PRIVATE_AND_PUBLIC: TODO: type description here.

    """

    PRIVATE = 'private'

    PUBLIC = 'public'

    PRIVATE_AND_PUBLIC = 'private_and_public'
