# -*- coding: utf-8 -*-

"""
mergedapi

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""
from mergedapi.api_helper import APIHelper
from mergedapi.models.vault_integration import VaultIntegration


class Extra(object):

    """Implementation of the 'Extra' model.

    TODO: type model description here.

    Attributes:
        vault_integration (VaultIntegration): TODO: type description here.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "vault_integration": 'vaultIntegration'
    }

    _optionals = [
        'vault_integration',
    ]

    def __init__(self,
                 vault_integration=APIHelper.SKIP):
        """Constructor for the Extra class"""

        # Initialize members of the class
        if vault_integration is not APIHelper.SKIP:
            self.vault_integration = vault_integration 

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Creates an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if dictionary is None:
            return None

        # Extract variables from the dictionary

        vault_integration = VaultIntegration.from_dictionary(dictionary.get('vaultIntegration')) if 'vaultIntegration' in dictionary.keys() else APIHelper.SKIP
        # Return an object of this model
        return cls(vault_integration)
