# -*- coding: utf-8 -*-

"""
mergedapi

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class FirmwareTypeEnumListEnum(object):

    """Implementation of the 'FirmwareTypeEnumList' enum.

    append or remove

    Attributes:
        APPEND: TODO: type description here.
        REMOVE: TODO: type description here.

    """

    APPEND = 'append'

    REMOVE = 'remove'
