# -*- coding: utf-8 -*-

"""
mergedapi

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class HelmHelmrepo(object):

    """Implementation of the 'helmHelmrepo' model.

    helmHelmrepo would have HelmChartName and HelmChartVersion.

    Attributes:
        helm_chart_name (string): The user can provide the Helm chart name.
        helm_chart_version (string): The user can provide the Helm chart
            version.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "helm_chart_name": 'helmChartName',
        "helm_chart_version": 'helmChartVersion'
    }

    def __init__(self,
                 helm_chart_name=None,
                 helm_chart_version=None):
        """Constructor for the HelmHelmrepo class"""

        # Initialize members of the class
        self.helm_chart_name = helm_chart_name 
        self.helm_chart_version = helm_chart_version 

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Creates an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if dictionary is None:
            return None

        # Extract variables from the dictionary

        helm_chart_name = dictionary.get("helmChartName") if dictionary.get("helmChartName") else None
        helm_chart_version = dictionary.get("helmChartVersion") if dictionary.get("helmChartVersion") else None
        # Return an object of this model
        return cls(helm_chart_name,
                   helm_chart_version)
