# -*- coding: utf-8 -*-

"""
mergedapi

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class HookTypeEnum(object):

    """Implementation of the 'hookType' enum.

    Allowed values:PRE_INSTALLATION, POST_INSTALLATION.

    Attributes:
        PRE_INSTALLATION: TODO: type description here.
        POST_INSTALLATION: TODO: type description here.

    """

    PRE_INSTALLATION = 'PRE_INSTALLATION'

    POST_INSTALLATION = 'POST_INSTALLATION'
