# -*- coding: utf-8 -*-

"""
mergedapi

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""
from mergedapi.api_helper import APIHelper


class ListString(object):

    """Implementation of the 'ListString' model.

    The ID of the target to delete, in the format {"id":
    "dd1682d3-2d80-cefc-f3ee-25154800beff"}.

    Attributes:
        id (string): TODO: type description here.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "id": 'id'
    }

    _optionals = [
        'id',
    ]

    def __init__(self,
                 id=APIHelper.SKIP):
        """Constructor for the ListString class"""

        # Initialize members of the class
        if id is not APIHelper.SKIP:
            self.id = id 

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Creates an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if dictionary is None:
            return None

        # Extract variables from the dictionary

        id = dictionary.get("id") if dictionary.get("id") else APIHelper.SKIP
        # Return an object of this model
        return cls(id)
