# -*- coding: utf-8 -*-

"""
mergedapi

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""
from mergedapi.api_helper import APIHelper


class LocationReportResponse(object):

    """Implementation of the 'LocationReportResponse' model.

    TODO: type model description here.

    Attributes:
        txid (string): The transaction ID of the report
        status (ReportStatusEnum): Status of the report
        estiamted_duration (string): Estimated number of minutes required to
            complete the report

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "txid": 'txid',
        "status": 'status',
        "estiamted_duration": 'estiamtedDuration'
    }

    _optionals = [
        'txid',
        'status',
        'estiamted_duration',
    ]

    def __init__(self,
                 txid=APIHelper.SKIP,
                 status=APIHelper.SKIP,
                 estiamted_duration=APIHelper.SKIP):
        """Constructor for the LocationReportResponse class"""

        # Initialize members of the class
        if txid is not APIHelper.SKIP:
            self.txid = txid 
        if status is not APIHelper.SKIP:
            self.status = status 
        if estiamted_duration is not APIHelper.SKIP:
            self.estiamted_duration = estiamted_duration 

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Creates an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if dictionary is None:
            return None

        # Extract variables from the dictionary

        txid = dictionary.get("txid") if dictionary.get("txid") else APIHelper.SKIP
        status = dictionary.get("status") if dictionary.get("status") else APIHelper.SKIP
        estiamted_duration = dictionary.get("estiamtedDuration") if dictionary.get("estiamtedDuration") else APIHelper.SKIP
        # Return an object of this model
        return cls(txid,
                   status,
                   estiamted_duration)
