# -*- coding: utf-8 -*-

"""
mergedapi

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""
from mergedapi.api_helper import APIHelper
from mergedapi.models.ok_response_item import OKResponseItem


class LocationOKResponse(object):

    """Implementation of the 'LocationOKResponse' model.

    TODO: type model description here.

    Attributes:
        mecsites (list of OKResponseItem): TODO: type description here.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "mecsites": 'mecsites'
    }

    _optionals = [
        'mecsites',
    ]

    def __init__(self,
                 mecsites=APIHelper.SKIP):
        """Constructor for the LocationOKResponse class"""

        # Initialize members of the class
        if mecsites is not APIHelper.SKIP:
            self.mecsites = mecsites 

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Creates an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if dictionary is None:
            return None

        # Extract variables from the dictionary

        mecsites = None
        if dictionary.get('mecsites') is not None:
            mecsites = [OKResponseItem.from_dictionary(x) for x in dictionary.get('mecsites')]
        else:
            mecsites = APIHelper.SKIP
        # Return an object of this model
        return cls(mecsites)
