# -*- coding: utf-8 -*-

"""
mergedapi

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class NetworkNatModeEnum(object):

    """Implementation of the 'NetworkNatModeEnum' enum.

    TODO: type enum description here.

    Attributes:
        HIGHAVAILABLE: TODO: type description here.
        SINGLE: TODO: type description here.
        DISABLE: TODO: type description here.

    """

    HIGHAVAILABLE = 'highAvailable'

    SINGLE = 'single'

    DISABLE = 'disable'
