# -*- coding: utf-8 -*-

"""
mergedapi

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class RepositoryTypeEnum(object):

    """Implementation of the 'repositoryType' enum.

    Type for the repository which can be Git or Helm.

    Attributes:
        GIT: TODO: type description here.
        HELM: TODO: type description here.

    """

    GIT = 'Git'

    HELM = 'Helm'
