# -*- coding: utf-8 -*-

"""
mergedapi

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class RepositoryResTypeEnum(object):

    """Implementation of the 'RepositoryResTypeEnum' enum.

    TODO: type enum description here.

    Attributes:
        GIT: TODO: type description here.
        HELM: TODO: type description here.
        USERUPLOAD: TODO: type description here.

    """

    GIT = 'Git'

    HELM = 'Helm'

    USERUPLOAD = 'userUpload'
