# -*- coding: utf-8 -*-

"""
mergedapi

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class ResponseCodeEnum(object):

    """Implementation of the 'ResponseCode' enum.

    An enumerated string with one of the following values - INVALID_ACCESS,
    INVALID_PARAMETER, INTERNAL_ERROR, SUCCESS.

    Attributes:
        INVALID_ACCESS: TODO: type description here.
        INVALID_PARAMETER: TODO: type description here.
        INTERNAL_ERROR: TODO: type description here.
        SUCCESS: TODO: type description here.

    """

    INVALID_ACCESS = 'INVALID_ACCESS'

    INVALID_PARAMETER = 'INVALID_PARAMETER'

    INTERNAL_ERROR = 'INTERNAL_ERROR'

    SUCCESS = 'SUCCESS'
