# -*- coding: utf-8 -*-

"""
mergedapi

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""
from mergedapi.api_helper import APIHelper


class RestErrorResponse2(object):

    """Implementation of the 'RestErrorResponse2' model.

    TODO: type model description here.

    Attributes:
        error_code (string): TODO: type description here.
        error_message (string): TODO: type description here.
        error_url (string): TODO: type description here.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "error_code": 'errorCode',
        "error_message": 'errorMessage',
        "error_url": 'errorUrl'
    }

    _optionals = [
        'error_code',
        'error_message',
        'error_url',
    ]

    def __init__(self,
                 error_code=APIHelper.SKIP,
                 error_message=APIHelper.SKIP,
                 error_url=APIHelper.SKIP):
        """Constructor for the RestErrorResponse2 class"""

        # Initialize members of the class
        if error_code is not APIHelper.SKIP:
            self.error_code = error_code 
        if error_message is not APIHelper.SKIP:
            self.error_message = error_message 
        if error_url is not APIHelper.SKIP:
            self.error_url = error_url 

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Creates an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if dictionary is None:
            return None

        # Extract variables from the dictionary

        error_code = dictionary.get("errorCode") if dictionary.get("errorCode") else APIHelper.SKIP
        error_message = dictionary.get("errorMessage") if dictionary.get("errorMessage") else APIHelper.SKIP
        error_url = dictionary.get("errorUrl") if dictionary.get("errorUrl") else APIHelper.SKIP
        # Return an object of this model
        return cls(error_code,
                   error_message,
                   error_url)
