# -*- coding: utf-8 -*-

"""
mergedapi

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class ServiceTypeEnum(object):

    """Implementation of the 'serviceType' enum.

    Service Type. Ex: Installation, Operations, Custom.

    Attributes:
        MY_SERVICE: TODO: type description here.

    """

    MY_SERVICE = 'MY_SERVICE'
