# -*- coding: utf-8 -*-

"""
mergedapi

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""
from mergedapi.api_helper import APIHelper
from mergedapi.models.daily_usage_item import DailyUsageItem


class SessionLevel(object):

    """Implementation of the 'SessionLevel' model.

    Session Report for a Device

    Attributes:
        sessions (list of DailyUsageItem): Contains only dates when device had
            sessions
        id (string): The 10-digit ID of the device.
        txid (string): A unique string that associates the request with the
            location report information that is sent in asynchronous callback
            message.ThingSpace will send a separate callback message for each
            device that was in the request. All of the callback messages will
            have the same txid.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "id": 'id',
        "txid": 'txid',
        "sessions": 'sessions'
    }

    _optionals = [
        'sessions',
    ]

    def __init__(self,
                 id=None,
                 txid=None,
                 sessions=APIHelper.SKIP):
        """Constructor for the SessionLevel class"""

        # Initialize members of the class
        if sessions is not APIHelper.SKIP:
            self.sessions = sessions 
        self.id = id 
        self.txid = txid 

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Creates an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if dictionary is None:
            return None

        # Extract variables from the dictionary

        id = dictionary.get("id") if dictionary.get("id") else None
        txid = dictionary.get("txid") if dictionary.get("txid") else None
        sessions = None
        if dictionary.get('sessions') is not None:
            sessions = [DailyUsageItem.from_dictionary(x) for x in dictionary.get('sessions')]
        else:
            sessions = APIHelper.SKIP
        # Return an object of this model
        return cls(id,
                   txid,
                   sessions)
