# -*- coding: utf-8 -*-

"""
mergedapi

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""
from mergedapi.api_helper import APIHelper
from mergedapi.models.parameters import Parameters


class SetAnomalyRequest(object):

    """Implementation of the 'setAnomalyRequest' model.

    Anomaly detection request.

    Attributes:
        account_name (string): The name of a billing account. An account name
            is usually numeric, and must include any leading zeros.
        request_type (string): The type of request being made. anomaly is the
            request to activate Anomaly Detection.
        sensitivity_parameter (list of Parameters): The initial values and
            monitoring state for abnormal and very abnormal.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "account_name": 'accountName',
        "request_type": 'requestType',
        "sensitivity_parameter": 'sensitivityParameter'
    }

    _optionals = [
        'account_name',
        'request_type',
        'sensitivity_parameter',
    ]

    def __init__(self,
                 account_name=APIHelper.SKIP,
                 request_type=APIHelper.SKIP,
                 sensitivity_parameter=APIHelper.SKIP):
        """Constructor for the SetAnomalyRequest class"""

        # Initialize members of the class
        if account_name is not APIHelper.SKIP:
            self.account_name = account_name 
        if request_type is not APIHelper.SKIP:
            self.request_type = request_type 
        if sensitivity_parameter is not APIHelper.SKIP:
            self.sensitivity_parameter = sensitivity_parameter 

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Creates an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if dictionary is None:
            return None

        # Extract variables from the dictionary

        account_name = dictionary.get("accountName") if dictionary.get("accountName") else APIHelper.SKIP
        request_type = dictionary.get("requestType") if dictionary.get("requestType") else APIHelper.SKIP
        sensitivity_parameter = None
        if dictionary.get('sensitivityParameter') is not None:
            sensitivity_parameter = [Parameters.from_dictionary(x) for x in dictionary.get('sensitivityParameter')]
        else:
            sensitivity_parameter = APIHelper.SKIP
        # Return an object of this model
        return cls(account_name,
                   request_type,
                   sensitivity_parameter)
