# -*- coding: utf-8 -*-

"""
mergedapi

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class Status2Enum(object):

    """Implementation of the 'Status2' enum.

    QUEUED or COMPLETED. Requests for IoT devices with cacheMode=0 (cached)
    have status=COMPLETED; all other requests are QUEUED.

    Attributes:
        QUEUED: TODO: type description here.
        COMPLETED: TODO: type description here.

    """

    QUEUED = 'QUEUED'

    COMPLETED = 'COMPLETED'
