# -*- coding: utf-8 -*-

"""
mergedapi

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class StatusEnum(object):

    """Implementation of the 'statusEnum' enum.

    Status of the MEC Platform (default is 'unknown')

    Attributes:
        ACTIVE: TODO: type description here.
        INACTIVE: TODO: type description here.
        UNKNOWN: TODO: type description here.

    """

    ACTIVE = 'Active'

    INACTIVE = 'Inactive'

    UNKNOWN = 'unknown'
