# -*- coding: utf-8 -*-

"""
mergedapi

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class StatusOfSandboxEnum(object):

    """Implementation of the 'Status of Sandbox' enum.

    Status of sandbox can have value like - NA, INPROGRESS, SUCCESS, FAILED.

    Attributes:
        NA: TODO: type description here.
        INPROGRESS: TODO: type description here.
        SUCCESS: TODO: type description here.
        FAILED: TODO: type description here.

    """

    NA = 'NA'

    INPROGRESS = 'INPROGRESS'

    SUCCESS = 'SUCCESS'

    FAILED = 'FAILED'
