# -*- coding: utf-8 -*-

"""
mergedapi

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class TemplateTypeEnum(object):

    """Implementation of the 'TemplateTypeEnum' enum.

    type of the template to be used for deployment

    Attributes:
        TERRAFORM: TODO: type description here.
        HEAT: TODO: type description here.
        CLOUDFORMATION: TODO: type description here.
        TOSCA: TODO: type description here.

    """

    TERRAFORM = 'Terraform'

    HEAT = 'Heat'

    CLOUDFORMATION = 'CloudFormation'

    TOSCA = 'TOSCA'
