# -*- coding: utf-8 -*-

"""
mergedapi

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class TypesUEIdentityTypeEnum(object):

    """Implementation of the 'types_UEIdentityType' enum.

    Type of User Equipment identifier used in `UEIdentity`.

    Attributes:
        IPADDRESS: TODO: type description here.

    """

    IPADDRESS = 'IPAddress'
