# -*- coding: utf-8 -*-

"""
mergedapi

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class WorkloadTypeEnum(object):

    """Implementation of the 'WorkloadTypeEnum' enum.

    default service type

    Attributes:
        CONTAINER: TODO: type description here.
        VIRTUALMACHINE: TODO: type description here.

    """

    CONTAINER = 'container'

    VIRTUALMACHINE = 'virtualMachine'
