# -*- coding: utf-8 -*-

"""
mergedapi

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class WorkloadUploadTypeEnum(object):

    """Implementation of the 'WorkloadUploadTypeEnum' enum.

    Allowed values are: GIT files (PULL_FROM_REPO), MANUAL_UPLOAD.

    Attributes:
        PULL_FROM_REPO: TODO: type description here.
        MANUAL_UPLOAD: TODO: type description here.

    """

    PULL_FROM_REPO = 'PULL_FROM_REPO'

    MANUAL_UPLOAD = 'MANUAL_UPLOAD'
